// GENERATED by scripts/stamp-build.mjs before every build. Do not edit.
// One value per build, imported by both the browser bundle and the server route
// so the two can never disagree about which build is running.
export const BUILD_ID = "muerkbzx";
export const BUILD_TIME = "2026-09-23T23:58:24.957Z";
// Typed as the union, not as the one literal that happens to be stamped today.
// Without the annotation TypeScript narrows this to a single string and then
// rejects every comparison against the other two as "no overlap", which fails
// the build on whichever environment is not the one last stamped locally.
export const BUILD_ENV: 'production' | 'preview' | 'development' = "development";
/** Every host that is really this app. The first is the one to share. */
export const CANONICAL_HOSTS: string[] = [];
/** The address to hand somebody. Empty when nothing was configured. */
export const CANONICAL_HOST: string = "";
